# WARNING : if using Volumes, you have to modify the folder right on the host.
# INFORMATION : To commentdecomment on Notepad++, use Ctrl+K / Ctrk+Q
 

#####################
# Individual version
#####################
version: "3.5"
services:
   telegraf:
    image: "telegraf"
    container_name: telegraf
    networks:
      - LoraNetwork
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf 
      
      
  influxdb:
    image: "influxdb"
    container_name: influxdb
    networks:
      - LoraNetwork
    ports:
      - "8086:8086"
    #volumes:
    # - ./data/influxdb:/var/lib/influxdb 
    environment:
      - INFLUXDB_DB=maBase 
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    restart: on-failure


  grafana:
    image: "grafana/grafana"
    container_name: grafana
    networks:
      - LoraNetwork
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    # volumes:
    # - ./data/grafana:/var/lib/grafana
    restart: on-failure
    
  chronograf:
    image: "chronograf"
    container_name: chronograf
    networks:
      - LoraNetwork    
    ports:
      - "8888:8888"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=admin
      # volumes:
      #- ./data/chronograf:/var/lib/chronograf
networks:
  LoraNetwork: 
    name: loraNetwork



