# ATTENTION : Pensez a modifier les droits des dossiers Volumes sur l'host
# To commentdecomment on Notepad++, use Ctrl+K / Ctrk+Q
# Alt + 3 repli les sections 

###########################################################################
# Version individuelle avec sauvegarde dans un dossier volume différent
###########################################################################
version: "3.5"
services:
  nodered:
    build: ./nodered-config
    container_name : nodered
    networks:
      - LoraNetwork
    ports:
      - "1880:1880"
    volumes:
      - ./data/:/data 
      - ./nodered-config/settings.js:/data/settings.js  
    restart: on-failure

networks:
  LoraNetwork: 
    name: loraNetwork



